👷 🐛 fix release action

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -11,6 +11,11 @@ on:
         description: 'New version or major, minor, patch'
         default: 'patch'
         required: true
+      retry:
+        description: "Retry release (clear created tag)"
+        default: false
+        required: true
+        type: boolean
 
 env:
   GH_BOT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
@@ -26,10 +31,9 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0
-          # Fine-grained PAT with contents:write and workflows:write
-          # scopes
-          token: ${{ secrets.CF_VOTES_RELEASE_ACTION }} # otherwise, you will failed to push refs to dest repo
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+          # Fine-grained PAT with contents:write and workflows:write scopes
+          token: ${{ secrets.CF_VOTES_RELEASE_ACTION }}
 
       - name: Use Node.js
         uses: actions/setup-node@v4
@@ -69,12 +73,22 @@ jobs:
         run: |
           VERSION=$(npm version ${INPUT_VERSION} --tag-version-prefix="" --no-git-tag-version)
 
+          echo ${VERSION}
+          BRANCH=release/${VERSION}
+
+          if git rev-parse "refs/tags/$VERSION" > /dev/null 2>&1; then
+            if [[ "${{ github.event.inputs.retry }}" = "true" ]]; then
+              gh release delete $VERSION --cleanup-tag --yes
+              git push origin --delete ${BRANCH} || true
+            else
+              echo "🛑 Tag $VERSION already exists"
+              exit 1
+            fi
+          fi
+
           # Update references from main to the new release branch
           sed -i "s|VOTE_ACTIONS_RELEASE: snapshot|VOTE_ACTIONS_RELEASE: '$VERSION'|" actions/count-votes/action.yml
           sed -i "s|count-votes@main|count-votes@$VERSION|" .github/workflows/receive-votes.yml
-
-          echo ${VERSION}
-          BRANCH=release/${VERSION}
 
           # Create a new branch for the release
           git checkout -b ${BRANCH}
